weather_limits = {'Cloudiness (C)': [-35, -20],
                  'Wind (kph)': [20, 40],
                  'Rain': [2400, 2000],
                  }

styles = {'p': {'font-family': 'Arial, Helvetica, sans-serif'},
          'table': {'font-family': 'Arial, Helvetica, sans-serif',
                    'border-collapse': 'collapse',
                    'margin-left': 'auto',
                    'margin-right': 'auto',
                    'border': '1px solid black',
                    'vertical-align': 'top',
                    'text-align': 'center',
                    'padding-top': '5px',
                    'padding-right': '5px',
                    'padding-bottom': '5px',
                    'padding-left': '5px',
                    },
          'tdc': {'font-family': 'Arial, Helvetica, sans-serif',
                  'border': '1px solid black',
                  'vertical-align': 'top',
                  'text-align': 'center',
                  'padding-top': '5px',
                  'padding-right': '5px',
                  'padding-bottom': '5px',
                  'padding-left': '5px',
                 },
          'tdr': {'font-family': 'Arial, Helvetica, sans-serif',
                  'border': '1px solid black',
                  'vertical-align': 'top',
                  'text-align': 'right',
                  'padding-top': '5px',
                  'padding-right': '5px',
                  'padding-bottom': '5px',
                  'padding-left': '5px',
                 },
          'tdl': {'font-family': 'Arial, Helvetica, sans-serif',
                  'border': '1px solid black',
                  'vertical-align': 'top',
                  'text-align': 'left',
                  'padding-top': '5px',
                  'padding-right': '5px',
                  'padding-bottom': '5px',
                  'padding-left': '5px',
                 },
         }