---
name: 'VYSOS-20'
logs_file_path: '/var/www/logs/V20'
plot_file_path: '/var/www/plots/V20'
temp_file_path: '/tmp/V20'
mongo_address: '192.168.1.101'
mongo_port: 27017
mongo_db: 'vysos'
mongo_collection: 'V20.images'
## Telescope Properties
focal_length: 4175            # mm
pixel_size: 9.0               # um
aperture: 508                 # mm
gain: 1.6                     # 1/ADU
saturation: 30000             # ADU
## Preferences
threshold_FWHM: 5.7           # pix (roughly 2.5 arcsec on VYSOS-20)
threshold_pointing_err: 4.0   # arcmin
threshold_ellipticity: 0.25
threshold_zeropoint: 19.9
units_for_FWHM: 'arcsec'
PSF_measurement_radius: 3000  # pix
pointing_marker_size: 1       # arcmin
## Source Extractor Parameters
SExtractor_params:
    PHOT_APERTURES: 16.0
    BACK_SIZE: 32
    SEEING_FWHM: 2.5
    SATUR_LEVEL: 50000
    DETECT_MINAREA: 5
    DETECT_THRESH: 2.0
    ANALYSIS_THRESH: 2.0
    FILTER: 'N'
    ASSOC_RADIUS: 10.0
## SCAMP Parameters
SCAMP_params:
    AHEADER_GLOBAL: '~/.VYSOS20.ahead'
    DISTORT_DEGREES: 1
    CROSSID_RADIUS: 10.0
    CHECKPLOT_TYPE: 'NONE'
    ASTREF_CATALOG: 'USNO-B1'
## Photometric Catalog Info
catalog:
#    name: 'USNO-B1.0'
#    columns: ['USNO-B1.0', 'RAJ2000', 'DEJ2000', 'R2mag', 'Imag']
#    magmax: 19.0
#    PSi: 'Imag'
#    PSr: 'R2mag'
    name: 'UCAC4'
    columns: ['_RAJ2000', '_DEJ2000', 'UCAC4', 'Vmag', 'gmag', 'rmag', 'imag']
    magmax: 19.0
    PSi: 'imag'
    PSr: 'rmag'
