---
name: 'VYSOS-5'
logs_file_path: '/var/www/logs/V5'
plot_file_path: '/var/www/plots/V5'
temp_file_path: '/tmp/V5'
mongo_address: '192.168.1.101'
mongo_port: 27017
mongo_db: 'vysos'
mongo_collection: 'V5.images'
## Telescope Properties
focal_length: 735             # mm
pixel_size: 9.0               # um
aperture: 135                 # mm
gain: 1.6                     # 1/ADU
saturation: 30000             # ADU
## Preferences
ROI: '[513:3584,513:3584]'
threshold_FWHM: 2.5           # pix
threshold_pointing_err: 5.0   # arcmin
threshold_ellipticity: 0.25
threshold_zeropoint: 18.7
units_for_FWHM: 'pix'
PSF_measurement_radius: 1024  # pix
pointing_marker_size: 3       # arcmin
## Source Extractor Parameters
SExtractor_params:
    PHOT_APERTURES: 6.0
    BACK_SIZE: 16
    SEEING_FWHM: 2.5
    SATUR_LEVEL: 50000
    DETECT_MINAREA: 4
    DETECT_THRESH: 5.0
    ANALYSIS_THRESH: 5.0
    FILTER: 'N'
    ASSOC_RADIUS: 10.0
## SCAMP Parameters
SCAMP_params:
    AHEADER_GLOBAL: '~/.VYSOS5.ahead'
    DISTORT_DEGREES: 5
    CROSSID_RADIUS: 10.0
    CHECKPLOT_TYPE: 'NONE'
    ASTREF_CATALOG: 'UCAC-3'
## Photometric Catalog Info
catalog:
    name: 'UCAC4'
    columns: ['_RAJ2000', '_DEJ2000', 'UCAC4', 'Vmag', 'gmag', 'rmag', 'imag']
    magmax: 16.0
    PSi: 'imag'
    PSr: 'rmag'
