---
name: 'VYSOS-20'
logs_file_path: '/var/www/plots/V20'
plot_file_path: '/var/www/plots/V20'
temp_file_path: '/tmp/V20'
## Telescope Properties
focal_length: 4175            # mm
pixel_size: 9.0               # um
aperture: 508                 # mm
gain: 1.6                     # 1/ADU
saturation: 30000             # ADU
## Preferences
threshold_FWHM: 5.7           # pix (roughly 2.5 arcsec on VYSOS-20)
threshold_pointing_err: 4.0   # arcmin
threshold_ellipticity: 0.25
threshold_zeropoint: 20.2
SCAMP_aheader: '~/.VYSOS20.ahead'
units_for_FWHM: 'arcsec'
PSF_measurement_radius: 2048  # pix
pointing_marker_size: 1       # arcmin
## Source Extractor Parameters
SExtractor_params:
    PHOT_APERTURES: 16.0
    BACK_SIZE: 32
    SEEING_FWHM: 2.5
    SATUR_LEVEL: 50000
    DETECT_MINAREA: 5
    DETECT_THRESH: 2.0
    ANALYSIS_THRESH: 2.0
    FILTER: 'N'
## SCAMP Parameters
SCAMP_params:
    DISTORT_DEGREES: 1
    CROSSID_RADIUS: 3
    CHECKPLOT_TYPE: 'NONE'
    ASTREF_CATALOG: 'USNO-B1'
## Photometric Catalog Info
catalog:
    name: 'UCAC4'
    magmax: 18.0
    PSi: 'imag'
    PSr: 'rmag'
    V: 'Vmag'
